version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classroom-frontend-app
    restart: always
    ports:
      - "5173:80"
    stdin_open: true
    tty: true
    networks:
      - classroom-network

networks:
  classroom-network:
    external: true
    name: student_managementbe_classroom-network
