version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classroom-frontend-app
    restart: always
    ports:
      - "5173:80"
    networks:
      - classroom-network

networks:
  classroom-network:
    driver: bridge
    name: classroom-network
