server {
    listen 80;
    server_name localhost;

    # Định tuyến cho Frontend (Single Page Application)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Định tuyến cho User Service (Cổng 8081) - ĐÃ BỎ BIẾN SET TRỰC TIẾP
    location /api/ {
        proxy_pass http://user-service-app:8081; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization $http_authorization; # Đảm bảo truyền token JWT ra môi trường thật
    }

    # Định tuyến cho Class Service (Cổng 8082) - ĐÃ BỎ BIẾN SET TRỰC TIẾP
    location /class-api/ {
        # Thực hiện rewrite trước để đưa URL về dạng /api/v1/classes/...
        rewrite ^/class-api/(.*)$ /api/$1 break;
        
        proxy_pass http://class-service-app:8082;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization $http_authorization; 
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}