server {
    listen 80;
    server_name localhost;

    resolver 127.0.0.11 valid=30s;

    # Định tuyến cho giao diện Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Định tuyến cho User Service (Giữ nguyên)
    location /api/ {
        set $user_backend user-service-app; 
        proxy_pass http://$user_backend:8081; 

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization $http_authorization; 
    }

    # Định tuyến cho Class Service: Dùng regex bóc tách trực tiếp bằng biến set
    location /class-api/ {
        # Sử dụng Regex ngay trong location để lấy phần URL phía sau
        if ($request_uri ~* ^/class-api/(.*)$) {
            set $class_uri $1;
        }
        
        set $class_backend class-service-app;
        
        # Nối chuỗi để đẩy URL chuẩn sang dạng /api/...
        proxy_pass http://$class_backend:8082/api/$class_uri;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization $http_authorization; 
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}