name: Frontend Production Deployment (Self-Hosted)

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-frontend:
    runs-on: self-hosted

    steps:
      - name: Checkout code từ GitHub
        uses: actions/checkout@v4

      - name: Ghi đè tự động file docker-compose.yml tối giản cho FE
        run: |
          echo 'version: "3.8"
          services:
            frontend:
              build:
                context: .
                dockerfile: Dockerfile
              container_name: classroom-frontend-app
              restart: always
              ports:
                - "5173:80"' > docker-compose.yml


      - name: Clean old Container avoid conflict
        run: |
          docker rm -f classroom-frontend-app || true

      - name: run Container Docker by Virtual Docker
        run: |
          docker compose build --build-arg VITE_API_URL="http://192.168.66.133:8081" frontend
          docker compose up -d frontend