name: Frontend Production Deployment (Self-Hosted)

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-frontend:
    runs-on: self-hosted

    steps:
      - name: Checkout code từ GitHub
        uses: actions/checkout@v4

      - name: Clean old Container avoid conflict
        run: |
          docker compose down || true
          
          TARGET_PORT_CONTAINER=$(docker ps -q --filter publish=5173)
          if [ ! -z "$TARGET_PORT_CONTAINER" ]; then
            echo "Phát hiện container $TARGET_PORT_CONTAINER đang chiếm cổng 5173. Tiến hành xóa..."
            docker rm -f $TARGET_PORT_CONTAINER
          fi

      - name: run Container Docker
        run: |
          # SỬA DÒNG NÀY: Truyền trực tiếp build-arg vào Docker Compose
          docker compose build --build-arg VITE_API_URL="http://192.168.66.133:8080/api" frontend
          docker compose up -d frontend